name: Deploy to AWS S3 (www website)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Deploy to AWS S3
        run: |
          aws s3 sync $SOURCE_DIR s3://$AWS_S3_BUCKET --acl public-read --region $AWS_REGION --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: www.aindriuodeasun.com
          AWS_REGION: eu-west-3
          SOURCE_DIR: .
